version: "3.1"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: golang
    restart: always
    ports:
      - "8113:8113"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    volumes:
      - ./src/prometheus:/etc/prometheus
      - prometheus_data:/src/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart: always

volumes:
  grafana-storage:
  prometheus_data:
